name: HWKMDElectronCI

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  job-macos-build:
    name: Build (MacOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true

    - name: Install UI deps
      run: |
        cd electron/ui
        npm install

    - name: build GUI
      run: |
        npm run build-electron
        cd ../

    - name: Install Electron deps
      run: |
        npm install

    - name: Install Electron build tools
      run: npm install -g electron-builder

    - name: Build
      run: |
        npm run dist
        tar -czvf hw-kmd-rewards-claim-desktop-osx.tar.gz dist

    - name: Upload hw-kmd-rewards-claim-desktop-osx.tar.gz as artifact
      uses: actions/upload-artifact@v1
      with:
        name: hw-kmd-rewards-claim-desktop-osx
        path: ./hw-kmd-rewards-claim-desktop-osx.tar.gz

  job-linux-build:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true

    - name: Build GUI
      run: |
        cd electron/ui
        npm install
        npm run build-electron

    - name: Build Electron App
      run: |
        cd electron
        npm install
        npm run dist
        tar -czvf hw-kmd-rewards-claim-desktop-linux.tar.gz dist
        ls -l

    - name: Upload hw-kmd-rewards-claim-desktop-linux.tar.gz as artifact
      uses: actions/upload-artifact@v1
      with:
        name: hw-kmd-rewards-claim-desktop-linux
        path: ./electron/hw-kmd-rewards-claim-desktop-linux.tar.gz

  job-win-build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true

    - name: Install UI deps
      run: |
        cd electron/ui
        npm install

    - name: build GUI
      run: |
        npm run build-electron
        cd ../

    - name: Install Electron deps
      run: |
        npm install

    - name: Build
      run: |
        npm run dist-win
        tar -czvf hw-kmd-rewards-claim-desktop-win.tar.gz dist

    - name: Upload hw-kmd-rewards-claim-desktop-win.tar.gz as artifact
      uses: actions/upload-artifact@v1
      with:
        name: hw-kmd-rewards-claim-desktop-win
        path: ./hw-kmd-rewards-claim-desktop-win.tar.gz