name: released

on:
  release:
    types: [created, unpublished, prereleased, released, published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: pbca26/ghaction-virustotal@v2.2.1
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          github_token: ${{ github.token }}
          update_release_body: true
          files: |
            hw-kmd-rewards-claim-desktop-linux-dev.tar.gz
            hw-kmd-rewards-claim-desktop-osx-dev.tar.gz
            hw-kmd-rewards-claim-desktop-wind-dev.tar.gz